_ = lambda x: x

# common codes
HELIXAUTH_ERROR = _('HELIXAUTH_ERROR')
HELIXAUTH_OBJECT_NOT_FOUND = _('HELIXAUTH_OBJECT_NOT_FOUND')
HELIXAUTH_OBJECT_ALREADY_EXISTS = _('HELIXAUTH_OBJECT_ALREADY_EXISTS')

# authorization errors
HELIXAUTH_SESSION_NOT_FOUND = _('HELIXAUTH_SESSION_NOT_FOUND')

# env errors
HELIXAUTH_ENVIRONMENT_NOT_FOUND = _('HELIXAUTH_ENVIRONMENT_NOT_FOUND')

# user errors
HELIXAUTH_USER_INACTIVE = _('HELIXAUTH_USER_INACTIVE')
HELIXAUTH_USER_AUTH_ERROR = _('HELIXAUTH_USER_AUTH_ERROR')