_ = lambda x: x

# common codes

HELIXAUTH_ERROR = _('HELIXAUTH_ERROR')
HELIXAUTH_OBJECT_NOT_FOUND = _('HELIXAUTH_OBJECT_NOT_FOUND')
HELIXAUTH_OBJECT_ALREADY_EXISTS = _('HELIXAUTH_OBJECT_ALREADY_EXISTS')

# env errors

# user errors