#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then

    . /usr/share/debconf/confmodule
    db_version 2.0

    #hostname 
    db_input high helixbilling/hostname || true
    db_go

    if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then

        dbc_dbname='helixbilling'
        dbc_dbuser='helixbilling'
        dbc_authmethod_user="password"

        . /usr/share/dbconfig-common/dpkg/config.pgsql
        dbc_go helixbilling $@
    fi

fi
