#!/bin/sh

set -e
#set -x

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    rm -f /etc/nginx/sites-enabled/helixbilling
    rm -f /etc/supervisor/process-enabled/helixbilling.ini

    if [ "$1" = "purge" ]; then
        rm -f  /etc/nginx/sites-available/helixbilling
        rm -rf /etc/nginx/sites-available/hilixbilling-ssl/
        rm -f /etc/supervisor/process-available/helixbilling.ini

        if [ -f /usr/share/debconf/confmodule ]; then
            . /usr/share/debconf/confmodule
            if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql  ]; then
                . /usr/share/dbconfig-common/dpkg/postrm.pgsql 
                dbc_go helixbilling $@
            fi
           
            db_purge || true
        fi
    fi

fi

CFG="/usr/share/python-support/helixbilling/helixbilling/conf/settings.py"
if [ -f $CFG ]; then
    rm -f $CFG
    if which ucf >/dev/null 2>&1; then
        ucf --debconf-ok --purge $CFG
    fi
fi

#DEBHELPER#
